/**
 * @description Test class for `HAM_ConstantsUtil`. No logics just holds the constants used across other HAM classes.
 * @Author : Cube84 - Ashwin S
 * @Last Modified By : Ashwin S
 * @Last Modified On : Sep 05, 2025
 * @Modification Log :
 * ==============================================================================
 * Ver | Date | Author | Modification
 *==============================================================================
 * 1.0 | Sep 05, 2025 |  Ashwin S | Initial Version
 * 2.0 | Jan 29, 2025 | Asheesh	  | Update
 */
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts, PMD.ApexUnitTestClassShouldHaveRunAs')
@IsTest
public class HAM_ConstantsUtil_Test {
    /**
     * @description Class holds just the constant. So adding the coverage by calling the constructor.
     */
    @IsTest
    static void testConstantsUtil() {
        HAM_ConstantsUtil constantsUtil = new HAM_ConstantsUtil();
    }
}